[package]
name         = "snakedown"
version      = "0.3.0"
authors      = ["aswlowwriter"]
edition      = "2024"
rust-version = "1.91"
description  = "This is a snakedown. Hand over your docs, nice and clean, and nobody gets confused."
readme       = "README.md"
license      = "MIT"

documentation = "https://docs.rs/snakedown"
repository    = "https://github.com/aslowwriter/snakedown"

[lib]
path  = "src/lib.rs"
bench = false

[[bin]]
path  = "src/main.rs"
name  = "snakedown"
bench = false

[profile.release]
debug         = 0
lto           = "fat"
codegen-units = 1
strip         = "symbols"

[profile.dev]
debug = 0

[profile.bench]
inherits = "release"
debug    = 2         # necessary for many profilers
strip    = "none"    #only affects binary size, not runtime, but makes profiling easier

[[bench]]
name    = "test_pkg"
harness = false

[dependencies]
base64              = "0.23.1"
clap                = { version = "4", features = ["derive", "unicode", "cargo"] }
clap-verbosity-flag = { version = "3.0.4", features = ["tracing"] }
color-eyre          = "0.6"
console             = "0.16.4"
dialoguer           = "0.12.0"
edit-distance       = "2.2.2"
flate2              = "1.1.9"
jupyter-protocol    = "2.0.2"

nbformat          = "3.0.0"
pyproject-toml    = "0.13.7"
reqwest           = { version = "0.13.4", features = ["blocking"] }
rustpython-parser = "0.4.0"

serde      = { version = "1", features = ["derive"] }
sphinx_inv = { version = "0.4.0" }
strum      = { version = "0.28.0", features = ["derive", "strum_macros"] }
tera       = "2.1.1"

tokio = { version = "1.53", features = [
  "rt",
  "rt-multi-thread",
  "io-util",
  "io-std",
  "time",
  "process",
  "macros",
  "fs",
  "parking_lot",
  "sync",
] }

toml               = "1.1.4"
tracing            = { version = "0", features = ["attributes"] }
tracing-error      = "0"
tracing-subscriber = "0"
url                = "2.5.8"
walkdir            = "2.5.0"
winnow             = { version = "1.0.4", features = ["simd"] }

[dev-dependencies]
assert_cmd        = "2.2.2"
assert_fs         = "1.1.4"
criterion         = { version = "0.8.2", features = ["async_tokio", "html_reports"] }
pretty_assertions = "1"
tempfile          = "3.27.0"
tracing-test      = "0.2.6"

# please tell me what to do Clippy-senpai
[lints.clippy]
single_match               = "warn"
single_match_else          = "warn"
needless_match             = "warn"
needless_late_init         = "warn"
redundant_pattern_matching = "warn"
redundant_pattern          = "warn"
redundant_guards           = "warn"
collapsible_match          = "warn"
match_single_binding       = "warn"
match_same_arms            = "warn"
match_ref_pats             = "warn"
match_bool                 = "warn"
needless_bool              = "deny"
unwrap_used                = "warn"
expect_used                = "warn"
